services:
  slurm-mira:
    image: dvalts/slurm-sim-cirrus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:8888:8888
      - 0.0.0.0:8787:8787
    volumes:
      - type: bind
        source: ./clusters
        target: /home/slurm/work
volumes:
  clusters:
